name: Deploy Node app to Azure Web App (mockapi)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # (Opcional) instala deps para validar package-lock, pero no compila nada
      - name: Install deps
        run: npm ci --omit=dev

      # Empaquetamos solo lo necesario; Oryx en App Service hará npm install allí
      - name: Prepare artifacts
        run: |
          mkdir build
          cp -r package.json package-lock.json server.js db.json build/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "mockapi"                               # <- tu Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build
